# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

    http_client:
        scoped_clients:
            stalwart.client:
                base_uri: '%env(STALWART_API_URL)%'
                headers:
                    Authorization: 'Bearer %env(STALWART_API_TOKEN)%'
                retry_failed:
                    enabled: true
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    jitter: 0.5

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
