framework:
    messenger:
        buses:
            messenger.bus.default:
                middleware:
                    - 'App\Messenger\Middleware\OpenTelemetryMiddleware'

        transports:
            sync: 'sync://'
            scheduler_default: 'sync://'

        routing:
            'App\Message\ProcessDeliveryEvent': sync
